### PR TITLE
format strings

### PR DESCRIPTION
**Pull request by h4ck3rm1k3**

### CODE REVIEW

**Comment by kiorky** [comment]
The cloud stuff is being totally rewritten to be based only on extpillar (via mc_pillar); so this changeset is now totally unrelated, sorry ;(.
On the other end, at the end of the rewrite, it will be much simpler, quickier, and straighforward to use :).
You can already have a glance of what was and is commited to see that things are moving on.

**Comment by kiorky** [comment]
btw im glad someone is looking that far on makina-states @h4ck3rm1k3 , if you have questions, feel free :).

**Comment by kiorky** [comment]
Did you saw: https://github.com/makinacorpus/mastersalt-pillar/blob/master/database.sample.yaml

But i need to update it to reflect changes after the cloud revamp.

**Comment by h4ck3rm1k3** [comment]
I have added your repos to my collection of salt examples https://github.com/h4ck3rm1k3/salt-formulas

**Comment by kiorky** [comment]
Ha, i hope that you understand that makina-states is much more that salt formulaes

**Comment by h4ck3rm1k3** [comment]
Well I am just looking for examples of salt I can test against and learn from.

**Comment by kiorky** [comment]
I'm closing it as it is unrelated now !

**Pull request closed without merging**
